

version: "1.0"
services:
  web:
    image: httpd:latest
    links:
      - db:database
    ports:
      - 80:80
    networks:
      - intranet
  dns:
    image: ubuntu/bind9
    volumes:
      - ./named.conf:/etc/bind/named.conf
    ports:
      - 53:53/udp
      - 53:53
    networks:
      - intranet

